; Inno Setup Script for We Share
; ULTIMATE PREMIUM LIGHT EDITION
; Generated by Antigravity

#define AppName "We Share"
#define AppVersion "1.0.0"
#define AppPublisher "Sowmiyan-S"
#define AppURL "https://github.com/sowmiyan-s/We-Share"
#define AppExeName "WeShare.Desktop.exe"
#define AppIcon "src\WeShare.UI\Assets\logo.ico"

[Setup]
AppId={{C7A9E5B2-D4A1-4F9C-B5A1-9E2F8B7D6C5A}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppCopyright=© 2026 {#AppPublisher}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
OutputDir=setup
OutputBaseFilename=WeShare_Setup
SetupIconFile={#AppIcon}
PrivilegesRequired=admin
WizardImageFile=design_assets\installer_banner_light.bmp
WizardSmallImageFile=src\WeShare.UI\Assets\logo_light.bmp
Compression=lzma2/ultra64
InternalCompressLevel=max
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#AppExeName}
DisableWelcomePage=no
WizardImageStretch=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "src\WeShare.UI\Assets\logo.ico"; DestDir: "{app}\Assets"; Flags: ignoreversion
Source: "src\WeShare.UI\Assets\logo.png"; DestDir: "{app}\Assets"; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\{#AppExeName}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#AppExeName}"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; Add Firewall Rule
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#AppName}"" dir=in action=allow program=""{app}\{#AppExeName}"" enable=yes"; Flags: runhidden
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#AppName}"" dir=out action=allow program=""{app}\{#AppExeName}"" enable=yes"; Flags: runhidden

[UninstallRun]
; Remove Firewall Rule
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#AppName}"""; Flags: runhidden

[Code]
var
  BaseColor: TColor;
  HeaderColor: TColor;
  TextColor: TColor;
  SubTextColor: TColor;
  AccentColor: TColor;

procedure InitializeWizard;
begin
  BaseColor := clWhite;
  HeaderColor := $FAFAFA; // Very light grey for header depth
  TextColor := $1A1A1A;   // Near black
  SubTextColor := $666666; // Grey
  AccentColor := $9333EA;  // Brand Purple

  // Global Backgrounds
  WizardForm.Color := BaseColor;
  WizardForm.InnerPage.Color := BaseColor;
  WizardForm.WelcomePage.Color := BaseColor;
  WizardForm.FinishedPage.Color := BaseColor;
  
  // Header Panel
  WizardForm.MainPanel.Color := BaseColor; // MATCHING LOGO BG
  WizardForm.PageNameLabel.Font.Color := TextColor;
  WizardForm.PageNameLabel.Font.Name := 'Segoe UI Semibold';
  WizardForm.PageNameLabel.Font.Size := 12;
  
  WizardForm.PageDescriptionLabel.Font.Color := SubTextColor;
  WizardForm.PageDescriptionLabel.Font.Name := 'Segoe UI';
  
  // Welcome & Finished Labels
  WizardForm.WelcomeLabel1.Font.Color := TextColor;
  WizardForm.WelcomeLabel1.Font.Size := 16;
  WizardForm.WelcomeLabel2.Font.Color := SubTextColor;
  
  WizardForm.FinishedHeadingLabel.Font.Color := TextColor;
  WizardForm.FinishedHeadingLabel.Font.Size := 16;
  WizardForm.FinishedLabel.Font.Color := SubTextColor;

  // Components on Pages
  WizardForm.SelectDirLabel.Font.Color := TextColor;
  WizardForm.SelectDirBrowseLabel.Font.Color := SubTextColor;
  WizardForm.SelectTasksLabel.Font.Color := TextColor;
  WizardForm.ReadyLabel.Font.Color := TextColor;
  WizardForm.ReadyMemo.Color := HeaderColor;
  WizardForm.ReadyMemo.Font.Color := SubTextColor;
  
  // Progress Page
  WizardForm.StatusLabel.Font.Color := TextColor;
  WizardForm.FileNameLabel.Font.Color := SubTextColor;
  
  // Buttons
  WizardForm.BackButton.Cursor := crHand;
  WizardForm.NextButton.Cursor := crHand;
  WizardForm.CancelButton.Cursor := crHand;

  // Remove Bevels for Flat Look
  WizardForm.Bevel.Visible := False;
  WizardForm.Bevel1.Visible := False;
  
  WizardForm.WizardBitmapImage.Stretch := True;
  WizardForm.WizardBitmapImage2.Stretch := True;
end;


procedure CurPageChanged(CurPageID: Integer);
begin
  WizardForm.InnerPage.Color := BaseColor;
  WizardForm.MainPanel.Color := BaseColor;
  
  if CurPageID = wpSelectTasks then
  begin
    WizardForm.TasksList.Color := BaseColor;
    WizardForm.TasksList.Font.Color := TextColor;
  end;
  
  if CurPageID = wpSelectDir then
  begin
    WizardForm.DirEdit.Color := BaseColor;
    WizardForm.DirEdit.Font.Color := TextColor;
  end;

  if CurPageID = wpSelectProgramGroup then
  begin
    WizardForm.GroupEdit.Color := BaseColor;
    WizardForm.GroupEdit.Font.Color := TextColor;
  end;
end;

function IsVCRedistInstalled: Boolean;
var
  Version: String;
begin
  // Check for Visual C++ 2015-2022 Redistributable (x64)
  Result := RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Version', Version);
end;

function InitializeSetup: Boolean;
begin
  Result := True;
  if not IsVCRedistInstalled then
  begin
    if MsgBox('The Visual C++ 2015-2022 Redistributable (x64) is required to run We Share but was not detected.' + #13#10#13#10 + 'Would you like to continue anyway? (The app may not start without it)', mbConfirmation, MB_YESNO) = IDNO then
    begin
      Result := False;
    end;
  end;
end;
