<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <ApplicationId>com.weshare.app</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <ZLibResourceCompression>true</ZLibResourceCompression>
    <Nullable>enable</Nullable>
    <AndroidEnableSGen>true</AndroidEnableSGen>
    <AndroidSdkDirectory>d:\PROJECTS\SHARE IT\android-sdk</AndroidSdkDirectory>
    <JavaSdkDirectory>d:\PROJECTS\SHARE IT\jdk-21-full\jdk-21.0.3+9</JavaSdkDirectory>
    <JavaHome>d:\PROJECTS\SHARE IT\jdk-21-full\jdk-21.0.3+9</JavaHome>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeShare.Core\WeShare.Core.csproj" />
    <ProjectReference Include="..\WeShare.UI\WeShare.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\WeShare.UI\Assets\**" LinkBase="Assets" />
  </ItemGroup>
</Project>
